"""Register of every image used in the report, the Kaggle Writeup and the repository:
what it shows, where its pixels come from, what was changed, and its licence.

    python scripts/image_register.py   # -> report/IMAGES.md, report/results/image_register.csv
"""
import fnmatch
import glob
import os

import pandas as pd
from PIL import Image

HELA = "HeLa \"Kyoto\" test well R05-C03 — R. Guiet (EPFL BIOP), Zenodo 10.5281/zenodo.6140064, CC BY 4.0"
HELA_TL = "HeLa \"Kyoto\" time-lapse, well R05-C03 field F0 — R. Guiet (EPFL BIOP), Zenodo 10.5281/zenodo.6139958, CC BY 4.0"
ISL = "Human iPSC-derived motor neurons (Condition A) — Christiansen et al., Cell 2018, gs://in-silico-labeling, CC BY 4.0"
CHART = "None (chart of numbers computed by this project)"
CC = "https://creativecommons.org/licenses/by/4.0/"
OURS = "CC BY 4.0 (figure by team Hack2Publish)"

# (glob pattern, what it shows, pixel source, modification, generated by)
RULES = [
    ("report/figures/qualitative_*.png", "Test images: bright-field input, real H2B, prediction, |error|, predicted σ", HELA, "full 540×540 fields, intensity-normalised, colour-mapped; predictions are model output", "scripts/make_figures.py"),
    ("report/figures/demo_panel_*.png", "Inference panel: bright-field, predicted nuclei, σ", HELA, "intensity-normalised, colour-mapped; prediction is model output", "scripts/inference.py"),
    ("report/figures/multiseed.png", "3-seed comparison of all configurations", CHART, "—", "scripts/make_figures_extra.py"),
    ("report/figures/shift_test.png", "Accuracy and σ under simulated distribution shifts", CHART, "—", "scripts/make_figures_extra.py"),
    ("report/figures/nucleus_gate.png", "Per-nucleus quality-gate curves", CHART, "—", "scripts/make_figures_extra.py"),
    ("report/figures/proliferation*.png", "Growth curves / doubling times from label-free counts", CHART, "—", "scripts/make_figures_extra.py"),
    ("report/figures/uncertainty_baselines*.png", "Uncertainty vs uncertainty-free proxies", CHART, "—", "scripts/make_figures_extra.py"),
    ("report/figures/ablation_arms*.png", "Extra ablation arms (LR, loss, β)", CHART, "—", "scripts/make_figures_extra.py"),
    ("report/figures/neural_*.png", "Neural transfer: bright-field, real DAPI, predictions, σ, fine-tuning curve", ISL, "rescaled to the HeLa pixel scale (factor chosen on validation wells), intensity-normalised, colour-mapped", "scripts/make_figures_extra.py"),
    ("report/figures/timelapse*.png", "60 h label-free nuclear read-out of one field", HELA_TL, "intensity-normalised, colour-mapped; counts are model/segmentation output", "scripts/make_figures_extra.py"),
    ("report/figures/failure_gallery.png", "Worst test images across seeds: input, real H2B, prediction, |error|, σ", HELA, "full fields, intensity-normalised, colour-mapped; predictions are model output", "scripts/make_figures_extra.py"),
    ("report/figures/sparsification_*.png", "Sparsification curves", CHART, "—", "scripts/make_figures.py"),
    ("report/figures/calibration_image_level.png", "Image-level σ vs MAE", CHART, "—", "scripts/make_figures.py"),
    ("report/figures/uncertainty_quality.png", "Uncertainty quality bars (seed 0)", CHART, "—", "scripts/make_figures.py"),
    ("report/figures/ablation.png", "Seed-0 ablation bars (superseded by multiseed.png)", CHART, "—", "scripts/make_figures.py"),
    ("report/figures/training_curves.png", "Validation curves per epoch", CHART, "—", "scripts/make_figures.py"),
    ("writeup/assets/cover_560x280.png", "Kaggle cover / thumbnail", HELA, "380×380 crop of field F3 t150, resized, colour-mapped, title text added", "inline script (see git history)"),
    ("writeup/assets/thumbnail_*.png", "Kaggle thumbnail variants", HELA, "crop of field F3 t150, resized, colour-mapped, text added", "inline script (see git history)"),
    ("writeup/assets/gallery_*.png", "Kaggle media-gallery copies of report figures", HELA + " (photographic panels) / none (charts)", "copies of report/figures/*", "cp"),
    ("demo/examples/*_blur1px.tif", "Demo input with simulated defocus", HELA, "Gaussian blur σ = 1 px applied by this project", "inline script (see git history)"),
    ("demo/examples/*.tif", "Demo inputs and matching real H2B", HELA, "unmodified (H2B: channel 1 of the original 2-channel file)", "copied from the dataset"),
]


def check_generators():
    missing = sorted({gen for *_, gen in RULES if gen.startswith("scripts/") and not os.path.exists(gen)})
    if missing:
        raise SystemExit(f"image register cites generator scripts that do not exist: {missing}")


def describe(path):
    for pat, what, src, mod, gen in RULES:
        if fnmatch.fnmatch(path, pat):
            return what, src, mod, gen
    return "UNREGISTERED — describe me", "?", "?", "?"


def main():
    check_generators()
    files = sorted(set(glob.glob("report/figures/*.png") + glob.glob("writeup/assets/*.png") + glob.glob("demo/examples/*.tif")))
    rows = []
    for f in files:
        try:
            w, h = Image.open(f).size
        except Exception:  # noqa: BLE001 - 16-bit TIFFs PIL cannot open
            import tifffile
            sh = tifffile.imread(f).shape
            h, w = sh[-2], sh[-1]
        what, src, mod, gen = describe(f)
        rows.append({"file": f, "pixels": f"{w}×{h}", "shows": what, "pixel_source": src, "modification": mod,
                     "generated_by": gen, "licence": OURS if src == CHART or "figures" in f or "assets" in f else "CC BY 4.0 (original data licence)"})
    df = pd.DataFrame(rows)
    os.makedirs("report/results", exist_ok=True)
    df.to_csv("report/results/image_register.csv", index=False)
    md = ["# Image register", "",
          "Every image used in the technical report, the Kaggle Writeup (cover, thumbnail, gallery) and the repository.",
          f"All microscopy pixels come from openly licensed CC BY 4.0 datasets ({CC}); figures that contain them are",
          "derivative works, shared under CC BY 4.0 with the attribution given in each row. Charts contain no dataset pixels.", "",
          "| File | Size (px) | Shows | Pixel source | Changes made | Made by |", "|---|---|---|---|---|---|"]
    for r in rows:
        md.append(f"| `{r['file']}` | {r['pixels']} | {r['shows']} | {r['pixel_source']} | {r['modification']} | `{r['generated_by']}` |")
    unreg = [r["file"] for r in rows if r["shows"].startswith("UNREGISTERED")]
    md += ["", f"{len(rows)} images registered" + (f"; UNREGISTERED: {unreg}" if unreg else "; none unregistered.")]
    open("report/IMAGES.md", "w").write("\n".join(md) + "\n")
    print("\n".join(md[-1:]))


if __name__ == "__main__":
    main()
